theme: jekyll-theme-cayman

# Site settings
title: Jacoe's Blog
description: "To Be Continued..."
url: "https://jacoesad.github.io"

# Build settings
paginate: 10

# Markdown
markdown: kramdown
kramdown:
  input: GFM

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# github
github:
  is_project_page: true